Introduced InTheFuture and InThePast specifications.
tkaczmarzyk/specification-arg-resolver pull request #160
Opened 2022-12-20 08:36 UTC by klesniak1

2022-12-28 13:30 UTC, jradlica commented on src/test/java/net/kaczmarzyk/spring/data/jpa/domain/InTheFutureTest.java
> +				.build(em);
Please verify is there any way to increasing the test data readability.

By adding comment like:
```
/*
*          | registration | next special offer | birth date | last order time
* ------  | ------------ | ------------------ | ---------- | ----------------
* HOMER   |    FUTURE    |       FUTURE       |    PAST    |    FUTURE
* MARGE   |    FUTURE    |       PAST         |   FUTURE   |    FUTURE
* MOE        |    PAST      |      FUTURE        |   FUTURE   |     PAST
*/
```
or by extending the customer builder:
```
		customer("Homer", "Simpson").with(
						REGISTRATION_DATE, IN_THE_FUTURE
						NEXT_SPECIAL_OFFER, IN_THE_FUTURE
						BIRTH_DATE, IN_THE_PAST,
						LAST_ORDER_TIME, FUTURE_DATE_TIME
				).build(em);
```
or
```
		customercustomer("Homer", "Simpson")
                  .withAllDatesInTheFuture()
                  .withBirthDate(IN_THE_PAST).build(em);
```

2022-12-29 12:04 UTC, tkaczmarzyk requested changes

2022-12-29 12:04 UTC, tkaczmarzyk commented on src/main/java/net/kaczmarzyk/spring/data/jpa/domain/InTheFuture.java
> +		Expression<TimeType> currentTimestamp = (Expression<TimeType>) cb.function("CURRENT_TIMESTAMP", rootPath.getClass());
have you verified that this is supported on JPA-level and/or which databases support it?

2022-12-29 12:04 UTC, tkaczmarzyk commented on src/test/java/net/kaczmarzyk/spring/data/jpa/Customer.java
> +	private Calendar registrationCalendar;
invalid formatting

2022-12-29 12:04 UTC, tkaczmarzyk commented on src/test/java/net/kaczmarzyk/spring/data/jpa/Customer.java
> +	private Timestamp dateOfNextSpecialOfferTimestamp;
invalid formatting

2022-12-29 12:04 UTC, tkaczmarzyk commented on src/test/java/net/kaczmarzyk/spring/data/jpa/Customer.java
> +	    this.registrationCalendar = Calendar.getInstance();
invalid formatting

2022-12-29 12:50 UTC, tkaczmarzyk requested changes

2022-12-29 12:50 UTC, tkaczmarzyk commented on src/main/java/net/kaczmarzyk/spring/data/jpa/domain/InThePast.java
> + * <p>Filters with ">" where-clause (e.g. {@code where dateOfBirth < localtimestamp()).</p>
">" --> "<"

2022-12-29 12:50 UTC, tkaczmarzyk commented on src/test/java/net/kaczmarzyk/spring/data/jpa/Customer.java
> + * <p>
why did you add it?

2022-12-29 12:50 UTC, tkaczmarzyk commented on src/test/java/net/kaczmarzyk/spring/data/jpa/Customer.java
> + * <p>
generally the license headers are managed automatically via Maven license plugin

2022-12-29 13:06 UTC, tkaczmarzyk approved these changes

2022-12-29 13:06 UTC, merged