Added setting default time during conversion from date to time storing formats
tkaczmarzyk/specification-arg-resolver pull request #161
Opened 2022-12-22 12:26 UTC by gotfrydoh

2022-12-28 13:39 UTC, jradlica approved these changes

2022-12-29 10:41 UTC, tkaczmarzyk requested changes

2022-12-29 10:41 UTC, tkaczmarzyk commented on src/test/java/net/kaczmarzyk/e2e/converter/TimestampE2eTest.java
> +	@Controller
fix formatting

2022-12-29 10:41 UTC, tkaczmarzyk commented on src/test/java/net/kaczmarzyk/e2e/converter/TimestampE2eTest.java
> +public class TimestampE2eTest extends E2eTestBase {
consider adding javadoc with `@author`

2022-12-29 10:41 UTC, tkaczmarzyk commented on src/test/java/net/kaczmarzyk/e2e/converter/TimestampE2eTest.java
> +		@RequestMapping(value = "/customers", params = "lastSeenBefore_customFormat")
please check formatting of the entire class

2022-12-29 10:41 UTC, tkaczmarzyk commented on src/test/java/net/kaczmarzyk/spring/data/jpa/Customer.java
> +	private Timestamp lastSeen;
formatting

2022-12-29 10:41 UTC, tkaczmarzyk commented on CHANGELOG.md
> +* added setting default time during conversion from date to time storing formats in `Converter`. Missing time values are filled with zeros (e.g. `LocalDateTime` format specified as `2022-12-14` will
added support for using datetime formats without time (e.g. `yyyy-MM-dd`) for types that contain time (`LocalDateTime`, `Timestamp`, `Instant`, `OffsetDateTime`). Missing time values are filled with zeros, e.g. when sending `2022-12-14` as `LocalDateTime` parameter, the conversion will result in `2022-12-14 00:00`.

2022-12-29 12:53 UTC, tkaczmarzyk approved these changes

2022-12-29 12:53 UTC, merged