Introduced `isMember` and `isNotMember` specifications
tkaczmarzyk/specification-arg-resolver pull request #208
Opened 2023-01-13 10:33 UTC by gotfrydoh

2023-01-13 14:04 UTC, tkaczmarzyk requested changes

2023-01-13 14:04 UTC, tkaczmarzyk commented on README.md
> +For example, for `luckyNumbers` table which contains association to `customers` table (one customer can have multiple lucky numbers) the following mapping can be introduced:
Let's simplify it:  For example, let's assume a Customer entity with lukcyNumber collection attribute (one customer can have multiple lucky numbers). The following mapping can be introduced:

2023-01-13 14:04 UTC, tkaczmarzyk commented on README.md
> +Supports collections of multiple data types: numbers, booleans, strings, dates, enums.
I'm assuming that this works only for @ELementCollection, not @oneTomany ? If so, then it's worth mentioning it.

2023-01-13 14:04 UTC, tkaczmarzyk commented on src/main/java/net/kaczmarzyk/spring/data/jpa/domain/IsFalse.java
> + * <p>Filters using `false` value for a boolean type field, i.e. tests for a false value.</p>
please also add the reference to Equal (see my previous comments, to be coped from readme)

2023-01-13 14:04 UTC, tkaczmarzyk commented on src/main/java/net/kaczmarzyk/spring/data/jpa/domain/IsMember.java
> +    private String expectedValue;
expectedMember?

2023-01-13 14:55 UTC, gotfrydoh commented on pom.xml
> +		</dependency>
We need `PluralAttributePath` from hibernate to obtain information about data type of element in Collection for `isMember` and `isNotMember` specifications. 
`Class<?> typeOnPath = ((PluralAttributePath<Object>) path(root)).getAttribute().getElementType().getJavaType();`

2023-01-16 10:00 UTC, tkaczmarzyk approved these changes

2023-01-16 14:19 UTC, tkaczmarzyk approved these changes

2023-01-16 14:20 UTC, merged